### GET request test(just to check whether the api is working or not?)
GET http://localhost:9090
### Get request display all the engineers
GET http://localhost:9090/api/v1/software-engineers

### Get request by ID like 1,2..
GET http://localhost:9090/api/v1/software-engineers/2

### Post it and check by Get request
POST http://localhost:9090/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Messi",
  "techStack": "Playmaking,AnkleBreak,Dominance"
}
### PUT(Update) a Record by ID
PUT http://localhost:9090/api/v1/software-engineers/2
Content-Type: application/json

{
  "name": "Ronaldo",
  "techStack": "Finishing, Discipline, HardWorker"
}
### Delete a Record by ID
DELETE http://localhost:9090/api/v1/software-engineers/1
